### ISSUE TITLE
SSL error in DB while executing processing -> processing_merge

### ISSUE THREAD

**Issue by mclerici** [eStation2/eStation2#68]
While running the processing Service (on mesa-proc), and activating the spot/proba-v merging (ID=4)
it goes in error as below. Looks like there is a conflict between the query (processing_merge -> line 61):

product_info = querydb.get_product_out_info(productcode=product_code,
                                                   subproductcode=sub_product_code,
                                                   version=version, echo=True)

and the one failing (processing.py -> line 61): 

active_processing_chains = querydb.get_active_processing_chains()

------------------------------------------------------ copy of the error -----------------------------------------
2015-05-15 14:46:16 - eStation2.apps.processing.processing - DEBUG - Entering infinite loop
2015-05-15 14:46:16 - eStation2.database.querydb - ERROR - get_processing_chains: Database query error!
 -> (psycopg2.DatabaseError) SSL error: decryption failed or bad record mac
 [SQL: 'SELECT processing_1.process_id AS processing_1_process_id, processing_1.defined_by AS processing_1_defined_by, processing_1.output_mapsetcode AS processing_1_output_mapsetcode, processing_1.derivation_method AS processing_1_derivation_method, processing_1.algorithm AS processing_1_algorithm, processing_1.priority AS processing_1_priority \nFROM products.processing AS processing_1 \nWHERE processing_1.activated = true']
Traceback (most recent call last):
  File "/srv/www/eStation2/apps/processing/drive_processing.py", line 41, in <module>
    processing.loop_processing(dry_run=dry_run)
  File "/srv/www/eStation2/apps/processing/processing.py", line 71, in loop_processing
    for chain in active_processing_chains:
TypeError: 'NoneType' object is not iterable

**Comment by mclerici** [comment]
This is due to the fact that the processing_merge() is launched as a detached process (~daemon), and, when is closed, somehow the connection to db is lost. Few solutions can be envisaged:
1. No use of any query in the processing modules (fttb, only 'merge' does)
2. Create in the 'processing_' modules ad-hoc connections (-> favorite)
3. Run the processing_merge() w/o detaching ..

**Comment by mclerici** [comment]
The following solution is under test: in the querydb.py module the connection is done within each query, i.e. the two lines below are moved from the 'header' to each function()

db = connectdb.ConnectDB().db
dbschema_analysis = connectdb.ConnectDB(schema='analysis').db

processing_merge() is now OK: any side effect ?

**Comment by mclerici** [comment]
For explaining the issue of closing connection on forking, see also:
http://www.postgresql.org/docs/9.3/static/libpq-connect.html
